### project configuration

# C++ project
language: cpp

# Use Ubuntu 14.04 (Trusty) 
dist: trusty
sudo: required
group: edge

branches:
  only:
    - master

git:
    submodules: true

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libboost-all-dev zlib1g-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo curl -L -o /root/cmake.sh https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo chmod +x /root/cmake.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo sudo /root/cmake.sh --exclude-subdir --prefix=/usr; fi

### build matrix
matrix:
  include:

    # Linux / GCC
    - os: linux
      compiler: gcc
      #env: 
      #  - COMPILER=g++-5
      #  - CXXFLAGS=-std=c++14
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'ninja-build']

### build script
script:
  # show OS/compiler version
  - uname -a
  - $CXX --version
  
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # Execute cmake
  - mkdir build
  - cd build
  - /usr/bin/cmake --version
  - /usr/bin/cmake ..
  - make
  - make test
