### project configuration

# C++ project
language: cpp

# Use Ubuntu 14.04 (Trusty)
dist: trusty
sudo: required
group: edge

branches:
  only:
    - master
    - develop

git:
    submodules: true

before_install:

  # Get version from git tag
  - export TRAVIS_TAG=$(git describe --abbrev=0 --tags)

  # define PLATFORM_ARTIFACT_NAME depending on TARGET_PLATFORM
  - if [ $TARGET_PLATFORM == android ]; then export PLATFORM_ARTIFACT_NAME=android-${TRAVIS_ANDROID_NDK_VERSION}-${TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION} ; fi
  - if [ $TARGET_PLATFORM == ios ]; then export PLATFORM_ARTIFACT_NAME=ios-sdk$(xcodebuild -showsdks | grep iphoneos | awk '{print $4}' | sed 's/[^0-9,\.]*//g') ; fi
  - if [ $TARGET_PLATFORM == linux ]; then export PLATFORM_ARTIFACT_NAME=ubuntu-trusty ; fi
  - if [ $TARGET_PLATFORM == macos ]; then export PLATFORM_ARTIFACT_NAME=macos-sdk$(xcodebuild -showsdks | grep macosx | awk '{print $4}' | sed 's/[^0-9,\.]*//g') ; fi

  # Install Linux Dependencies (zlib, cmake, Google Drive Downloader)
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install zlib1g-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo curl -L -o /root/cmake.sh https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo chmod +x /root/cmake.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo /root/cmake.sh --exclude-subdir --prefix=/usr; fi

  # Download Google Drive Downloader
  - curl -OL https://gist.githubusercontent.com/Manromen/4e4cf28ddf5bf2e4ee5cc2dfe4055952/raw/77d59731d3523f51d312254c6fd36427b3ea49b5/googleDriveDownload.sh
  - chmod +x googleDriveDownload.sh;

  # Install Android Boost / NDK / zlib from Google Drive
  # Boost NDK r17b
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r17b ]; then ./googleDriveDownload.sh "1WwOce4Ci89f56a0UsvaRHS-8SpeARagj" ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r17b ]; then unzip -q -o boost-android-r17b-15-clang-1.68.0.zip -d deps/; fi
  # Boost NDK r18
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then curl -L -o boost-android-r18-arm64-v8a-1.68.0.zip https://github.com/Manromen/Boost-for-Android/releases/download/Boost-1.68.0/boost-android-r18-arm64-v8a-1.68.0.zip ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then unzip -q -o boost-android-r18-arm64-v8a-1.68.0.zip -d deps/ ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then curl -L -o boost-android-r18-armeabi-v7a-1.68.0.zip https://github.com/Manromen/Boost-for-Android/releases/download/Boost-1.68.0/boost-android-r18-armeabi-v7a-1.68.0.zip ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then unzip -q -o boost-android-r18-armeabi-v7a-1.68.0.zip -d deps/ ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then curl -L -o boost-android-r18-x86-1.68.0.zip https://github.com/Manromen/Boost-for-Android/releases/download/Boost-1.68.0/boost-android-r18-x86-1.68.0.zip ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then unzip -q -o boost-android-r18-x86-1.68.0.zip -d deps/ ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then curl -L -o boost-android-r18-x86_64-1.68.0.zip https://github.com/Manromen/Boost-for-Android/releases/download/Boost-1.68.0/boost-android-r18-x86_64-1.68.0.zip ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then unzip -q -o boost-android-r18-x86_64-1.68.0.zip -d deps/ ; fi
  # NDK r17b
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r17b ]; then ./googleDriveDownload.sh "1TC5k_qcdZthAjLZOZG50iYdvzHO0n8ck" ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r17b ]; then unzip -q -o android-ndk-r17b-linux-x86_64.zip ; fi
  # NDK r18
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then ./googleDriveDownload.sh "107fT4NP2YMDyK89xp3l6NRzPnwxrr2HT" ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then unzip -q -o android-ndk-r18-linux-x86_64.zip ; fi
  # zlib NDK r17b
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r17b ]; then curl -L -o zlib-android-r17b-19-clang-1.2.11.zip "https://onedrive.live.com/download?cid=8269456C9AED2587&resid=8269456C9AED2587%21199253&authkey=${ONEDRIVE_AUTH_ZLIB}" ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r17b ]; then unzip -o zlib-android-r17b-19-clang-1.2.11.zip -d deps/; fi
  # zlib NDK r18
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then curl -L -o zlib-android-r18-19-clang-1.2.11.zip "https://onedrive.live.com/download?cid=8269456C9AED2587&resid=8269456C9AED2587%21199254&authkey=${ONEDRIVE_AUTH_ZLIB}" ; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TARGET_PLATFORM == android ] && [ $TRAVIS_ANDROID_NDK_VERSION == r18 ]; then unzip -o zlib-android-r18-19-clang-1.2.11.zip -d deps/; fi

    # Install iOS Boost and zlib from Google Drive
  - if [ $TARGET_PLATFORM == ios ]; then ./googleDriveDownload.sh "1ILxNcA5SS9_IVtHVMXsq6rmEUdVOsJ0w" ; fi
  - if [ $TARGET_PLATFORM == ios ]; then unzip -q -o boost-ios-sdk11.4-clang-1.68.0.zip -d deps/; fi
  - if [ $TARGET_PLATFORM == ios ]; then curl -L -o zlib-1.2.11-ios-sdk11.4.zip https://drive.google.com/uc\?export\=download\&id\=1PWK67Q-dGGZ6GKx3qOCFw9toD7bLqmTr ; fi
  - if [ $TARGET_PLATFORM == ios ]; then unzip -o zlib-1.2.11-ios-sdk11.4.zip -d deps/; fi

  # Install Linux Boost from Google Drive
  - if [ $TARGET_PLATFORM == linux ]; then ./googleDriveDownload.sh "1Z_bHUgDjVENLx5jjtD7OMgTafRuzT-zJ" ; fi
  - if [ $TARGET_PLATFORM == linux ]; then unzip -q -o boost-ubuntu-trusty-1.68.0.zip -d deps/; fi

  # Install macOS Boost and zlib from Google Drive
  - if [ $TARGET_PLATFORM == macos ]; then ./googleDriveDownload.sh "1HN3SLqjHDYP8G4QjIX92zB_tpBcAlgi-" ; fi
  - if [ $TARGET_PLATFORM == macos ]; then unzip -q -o boost-macos-sdk10.13-clang-1.68.0.zip -d deps/; fi
  - if [ $TARGET_PLATFORM == macos ]; then curl -L -o zlib-1.2.11-macos.zip https://drive.google.com/uc\?export\=download\&id\=1Nt0jndWSv_hZujCBneGAuINrVAH7uNW2 ; fi
  - if [ $TARGET_PLATFORM == macos ]; then unzip -o zlib-1.2.11-macos.zip -d deps/; fi

### build matrix
matrix:
  include:

    # Android / clang - NDK r17b
    - os: linux
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r17b
        - TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION=clang
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - secure: "ulNXdBvENG432FP/Lj8ju7lmIsrMJxCBeaIDR5a4zfjfU1f/Uj74f/kz2uEn+CR7dQzMueX/RJro6H8UuNbzwP1evE3IayufdnYXN2yfhE5rL2yxji8SAc0qEawYU5Eh6Usg2tf11mQmB1/zHWcEszD67NeFLrpfIB+4RpMDu/YuFE3vwhDHfrVtiXhz2xb0B0PfG9p29DIY/YzmDS2fp/FhCU9WsFdl9uVlbV/5jvRmeSkZkB0BmAimc+stxXRw4Gl38HlEqyWm+y4fRrDBsHSKusQDWJAexWtpM1RB3GQGgYg7EBsKKzVKOPcpw9diIYUmfLnbTejtDT8pIhLsYcar78tOZGuzaIu5T3p4PiHRKRAeHhbUu/ELf2UC7oupMTcZ2cfST2geUhhJJX5baE+pB2GHmdxob5mmkGi9hCXN4H1U1J6G4Uf/ek7n896hJgPC6jdi0KfdDnv2zt0BszJL1HFSWGGD84sOcya465B1dHTeqFKqTvqx9m075rdiAev0HLigamEkbR7al0hTkAlwcC3jvjo5sUNcC2tK9ie0DzNJIPehv/u4+StFQ/CIZJyT5WpWSbbubkVx9RqTzFltbEwIovgV3ODq2ZUvNi+D9+d53pPe7Zp3azsBKR5ACFez1ugm9HPXuO1k0Ha6pBvhiT79AQsP0kBZJGLq69w="
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

      # Android / clang - NDK r18
    - os: linux
      env:
        - TARGET_PLATFORM=android
        - TRAVIS_ANDROID_NDK_VERSION=r18
        - TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION=clang
        - TRAVIS_ANDROID_STL_TYPE=c++_static
        - secure: "KhWixoYYDjLzIhTFKy4mqYdxcVd2eIeJXsnUoQhy3afYOIeNVNx8VonIfVWFT3TyO0NvC8poTmugPNB4nQBx+S+TNoRGkQa9/8bpcCO1vWsfwj94NeMc8mEMo+1Q1bBNoBAgiuGvxTeAZCvxV3L7WEHysZJ4wa9Kh4qRyEnB9NJo5thBJiPuyG/UIaHzr6zGhP54fmB0l0GgIMHn4ugvVRIz7/BYDPJNsoYdPnhci6Jgv7mG9vIR+JVo62P4ngKQAli7tKKKlFipHOV6bf/x6HpvuRsbGXace8LukU/zJwP7JPiAFYfP3i2G7emT3URRAZUVf0gmunDF/cdPUI8AWorOfRSEJL6DTZSXMKMy9r5RY5KVoj5YR8wZCrefjCYolvbUXYBJuAx/JLHwltrPrLsnLvFjlgNsBJKvKYeyMyYAwvcMwcrZbVJOW+4Lf4iV9Te486sLMgeJuLdSukmQSWp5CH7Jf94GFvUQZZYmwM3vZvze95G9knWGVvAKhTAo8u4ewaynzqU9HbvKf8YOeGlWtMQcq//D12yYW3UWifTet478YBOIThiGXX0Mtuk4fNQhHsAAI9AYWynl/CcXxDFUaqT3NxJkMZ1k11XOWKLQTILoVbEZtnlbicT0DzMAS28/FKXW+vRTgvcyrkkC0YiV/mLbejMZDsgwS1tT/Z4="
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5' ]

    # iOS
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - TARGET_PLATFORM=ios

    # Linux / GCC
    - os: linux
      compiler: gcc
      env:
        - TARGET_PLATFORM=linux
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-5', 'ninja-build']

    # macOS
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - TARGET_PLATFORM=macos

### build script
script:
  # show OS/compiler version
  - uname -a

  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # create build / install folder
  - mkdir build; mkdir -p install/lib; cd build

  # Android build
  # API 19 ARCH armeabi-v7a
  - if [ $TARGET_PLATFORM == android ]; then /usr/bin/cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=19 -DCMAKE_ANDROID_NDK=${TRAVIS_BUILD_DIR}/android-ndk-${TRAVIS_ANDROID_NDK_VERSION} -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=${TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION} -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=${TRAVIS_ANDROID_STL_TYPE} -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/deps -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/deps/lib/armeabi-v7a -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install/armeabi-v7a" .. ; fi
  - if [ $TARGET_PLATFORM == android ]; then make install ; fi
  - if [ $TARGET_PLATFORM == android ]; then mv ${TRAVIS_BUILD_DIR}/install/armeabi-v7a/lib ${TRAVIS_BUILD_DIR}/install/lib/armeabi-v7a ; fi
  - if [ $TARGET_PLATFORM == android ]; then mv ${TRAVIS_BUILD_DIR}/install/armeabi-v7a/include ${TRAVIS_BUILD_DIR}/install/ ; fi
  - if [ $TARGET_PLATFORM == android ]; then rm -rf * ; fi
  # API 19 ARCH x86
  - if [ $TARGET_PLATFORM == android ]; then /usr/bin/cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=19 -DCMAKE_ANDROID_NDK=${TRAVIS_BUILD_DIR}/android-ndk-${TRAVIS_ANDROID_NDK_VERSION} -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=${TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION} -DCMAKE_ANDROID_ARCH_ABI=x86 -DCMAKE_ANDROID_STL_TYPE=${TRAVIS_ANDROID_STL_TYPE} -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/deps -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/deps/lib/x86 -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install/x86" .. ; fi
  - if [ $TARGET_PLATFORM == android ]; then make install ; fi
  - if [ $TARGET_PLATFORM == android ]; then mv ${TRAVIS_BUILD_DIR}/install/x86/lib ${TRAVIS_BUILD_DIR}/install/lib/x86 ; fi
  - if [ $TARGET_PLATFORM == android ]; then rm -rf * ; fi
  # API 21 ARCH arm64-v8a
  - if [ $TARGET_PLATFORM == android ]; then /usr/bin/cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_NDK=${TRAVIS_BUILD_DIR}/android-ndk-${TRAVIS_ANDROID_NDK_VERSION} -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=${TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION} -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_ANDROID_STL_TYPE=${TRAVIS_ANDROID_STL_TYPE} -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/deps -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/deps/lib/arm64-v8a -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install/arm64-v8a" .. ; fi
  - if [ $TARGET_PLATFORM == android ]; then make install ; fi
  - if [ $TARGET_PLATFORM == android ]; then mv ${TRAVIS_BUILD_DIR}/install/arm64-v8a/lib ${TRAVIS_BUILD_DIR}/install/lib/arm64-v8a ; fi
  - if [ $TARGET_PLATFORM == android ]; then rm -rf * ; fi
  # API 21 ARCH x86_64
  - if [ $TARGET_PLATFORM == android ]; then /usr/bin/cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_NDK=${TRAVIS_BUILD_DIR}/android-ndk-${TRAVIS_ANDROID_NDK_VERSION} -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=${TRAVIS_ANDROID_NDK_TOOLCHAIN_VERSION} -DCMAKE_ANDROID_ARCH_ABI=x86_64 -DCMAKE_ANDROID_STL_TYPE=${TRAVIS_ANDROID_STL_TYPE} -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/deps -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/deps/lib/x86_64 -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install/x86_64" .. ; fi
  - if [ $TARGET_PLATFORM == android ]; then make install ; fi
  - if [ $TARGET_PLATFORM == android ]; then mv ${TRAVIS_BUILD_DIR}/install/x86_64/lib ${TRAVIS_BUILD_DIR}/install/lib/x86_64 ; fi
  - if [ $TARGET_PLATFORM == android ]; then rm -rf * ; fi

  # iOS build
  - if [ $TARGET_PLATFORM == ios ]; then cmake  -DCMAKE_TOOLCHAIN_FILE="${TRAVIS_BUILD_DIR}/cmake/Toolchains/ios.toolchain.cmake" -DIOS_PLATFORM="OS" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install" -DCMAKE_PREFIX_PATH="${TRAVIS_BUILD_DIR}/deps" .. ; fi
  - if [ $TARGET_PLATFORM == ios ]; then make install ; fi

  # Linux build
  - if [ $TARGET_PLATFORM == linux ]; then /usr/bin/cmake "-DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/deps" -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install" -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/deps/lib/x86_64 .. ; fi
  - if [ $TARGET_PLATFORM == linux ]; then make ; fi
  - if [ $TARGET_PLATFORM == linux ]; then make install ; fi
  - if [ $TARGET_PLATFORM == linux ]; then make test ; fi

  # macOS build
  - if [ $TARGET_PLATFORM == macos ]; then cmake "-DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/deps" -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/install" .. ; fi
  - if [ $TARGET_PLATFORM == macos ]; then make ; fi
  - if [ $TARGET_PLATFORM == macos ]; then make install ; fi
  - if [ $TARGET_PLATFORM == macos ]; then make test ; fi

  # iOS ranlib
  - if [ $TARGET_PLATFORM == ios ]; then xcrun ranlib "${TRAVIS_BUILD_DIR}/install/lib/*.a" || true ; fi


# ZIP result
  - cd "${TRAVIS_BUILD_DIR}/install"
  - zip -r "${TRAVIS_BUILD_DIR}/rgpzip-${PLATFORM_ARTIFACT_NAME}-${TRAVIS_TAG}.zip" include lib
  - cd "${TRAVIS_BUILD_DIR}"

deploy:
  provider: releases
  api_key:
    secure: "PX+2uNPt8gLzs6uMek9ycsKjezQy5Da2rJSMPwZv6SiDt3yQU4LDp/K3VKVhV4y8Uks3FtUati1kYsdz6mzaalUV6mSkFZ+wHa6YR9fWxBYndtiiAuApHX3A3rsbO6j5r0dkG7auKt1iRLZwgE+U/rDNv55j94QEb2Ey7Nvx9Bwcdursin5iO3jleLApGoqOl7cDgVf0V1TylA6H5pdr26cSHDOK5XKwix4zlQ4Bk5gtJ9zT7uEWh+JZQgTUr1t7Q8Dx0KK+Cdce/Kf+qearHJZp/qBhnkp7HMMOjC7qUfU/dr97LZeVpZ6OCsiVS+oj1YzsyGGEiJV9YhnLZa6n+gRctlLbOBFtWKEKbCGXkwWS46aDV10Crziog8hna8UuK7YJ2tTVHV7W/fXQNP9txV5JGH1dvw5/DQebYwB9VTFi34u8k43yQDPgdpTjI7slGaBxNI5hRRE+sRrT9bt/CNx7ARw6V6BbQxIEDbebno/sb+eqd8wiTFEo4J+FvwL7u89oQIni0slu+vZuHeQPLPOu8nOyv61dBVOGZnjSOS8Yz/wRBLx4o1chnLMjciR2pRk3nDE5c+b38YYT6hob/dfaS6Cz0lwqImKK+Y0rLaVuG4nKH4ASm+eKLwdx5aM+vSOKwxpXrLGY79/nhioLh9RYO8xndobzn4PSFYjye9o="
  file: "rgpzip-${PLATFORM_ARTIFACT_NAME}-${TRAVIS_TAG}.zip"
  skip_cleanup: true
  on:
    branch: master
