version: '{build}'

image: Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      FLAGS: ""

init:
  - cmake --version
  - msbuild /version

install:
  # get submodules
  - git submodule update --init --recursive

  # store library version (via git tag) into environmental variable
  - ps: $env:LIBRARY_VERSION = & git describe --abbrev=0 --tags

  # set protocol to tls version 1.2
  - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
  # download google drive downloader script
  - ps: Invoke-WebRequest -Uri "https://gist.githubusercontent.com/Manromen/f1a306097d46a69a09c25ca34b79a804/raw/6dd8c29d719da3e33d19df028972e86ddcfd6e5f/googleDriveDownload.ps1" -OutFile "googleDriveDownload.ps1"

  # download boost for windows
  - ps: '& "./googleDriveDownload.ps1" -GoogleFileId 13V9TzP7JUaF6EkIUpXbg6CM1T71OmUGg -FileDestination "boost-win10-msvc14.1-mt-s-1.68.0.zip"'
  - ps: Expand-Archive -LiteralPath "boost-win10-msvc14.1-mt-s-1.68.0.zip" –DestinationPath "./deps"

  # download zlib for windows
  - ps: '& "./googleDriveDownload.ps1" -GoogleFileId 15Z1J96itQI0NFLWu1fz-OLMMCc58_eAb -FileDestination "zlib-win10-1.2.11.zip"'
  - ps: Expand-Archive -LiteralPath "zlib-win10-1.2.11.zip" –DestinationPath "./deps"

build_script:
  # cmake / build / install
  - ps: cmake -G "Visual Studio 15 2017" "-DCMAKE_BUILD_TYPE=RELEASE" "-DCMAKE_PREFIX_PATH=${env:APPVEYOR_BUILD_FOLDER}/deps" "-DCMAKE_LIBRARY_PATH=${env:APPVEYOR_BUILD_FOLDER}/deps/lib/x86" "-DCMAKE_INSTALL_PREFIX=${env:APPVEYOR_BUILD_FOLDER}/install" .
  - ps: cmake --build . --target INSTALL --config Release
  # - ps: cmake --build . --target RUN_TESTS --config Debug

after_build:
  - ps: Get-ChildItem -Path ${env:APPVEYOR_BUILD_FOLDER}\install
  # Archive include and lib folder into a ZIP file containing the library version
  - ps: Compress-Archive -Force -Path ${env:APPVEYOR_BUILD_FOLDER}\install\include, ${env:APPVEYOR_BUILD_FOLDER}\install\lib -DestinationPath rgpzip-win10-${env:LIBRARY_VERSION}.zip

artifacts:
  - path: rgpzip-win10-*.zip
    name: RGPZip-Win10

deploy:
  release: ${env:LIBRARY_VERSION}
  description: 'Windows 10'
  provider: GitHub
  auth_token:
    secure: dUid+CLSKyImcMCRy/23dH9Ue11Il5K7AB1r2r3/fAQfm3Lkc7EHuIE6NH4Dw8Up
  artifact: rgpzip-win10-*.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
